// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnlcVvZT3FuXHGnFOyPgnqA4vR4t_xh8Y',
    appId: '1:349864373143:web:1f068fcbbadae8a2f6f2d2',
    messagingSenderId: '349864373143',
    projectId: 'final-software-technology',
    authDomain: 'final-software-technology.firebaseapp.com',
    storageBucket: 'final-software-technology.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2hZm_CZigyrnGDdmBmgZjdyUVvxh_ZUg',
    appId: '1:349864373143:android:74704a3b2275b197f6f2d2',
    messagingSenderId: '349864373143',
    projectId: 'final-software-technology',
    storageBucket: 'final-software-technology.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCYouZaOYd2Kneelgzr_k_PLDsIOFjaA',
    appId: '1:349864373143:ios:7c7203125431865bf6f2d2',
    messagingSenderId: '349864373143',
    projectId: 'final-software-technology',
    storageBucket: 'final-software-technology.appspot.com',
    androidClientId: '349864373143-68ak8al66vrjs3nstm6g4n6u9e27rqm7.apps.googleusercontent.com',
    iosClientId: '349864373143-hnthk8q64chb6363sj4s9ipq6neh7dri.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakeMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCYouZaOYd2Kneelgzr_k_PLDsIOFjaA',
    appId: '1:349864373143:ios:066a64bd91fe93cff6f2d2',
    messagingSenderId: '349864373143',
    projectId: 'final-software-technology',
    storageBucket: 'final-software-technology.appspot.com',
    androidClientId: '349864373143-68ak8al66vrjs3nstm6g4n6u9e27rqm7.apps.googleusercontent.com',
    iosClientId: '349864373143-qstsmbv63piic9cl0cnh7o419fqstnb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fakeMessenger.RunnerTests',
  );
}
